ediardo/kmdr-cli

- README.md
Adds to description of kmdr and includes verbose instructions for how to use the tool.
> Make read-me more verbose

- README.md
List of programs currently supported by kmdr.
> Details of supported programs for explanations

- .dockerignore
- Dockerfile
- README.md
Instructions for building a docker image and running a container with `kmdr` in it.
> Dockerfile for running kmdr in a container

- README.md
Add missing programs from the list, please validate it and publish.
Fixes #22
> Update list of supported programs

- src/console.ts
- src/explain/explain.ts
- yarn.lock
Display a short error message when the query does not contain a known program by kmdr. This fix only applies to queries that produce a CommandNode tree
> Show error message

- README.md
This is the last program added to the list, it was created and added
> Add lsblk to the program list

- README.md
Use a better image quality for the gif
> Use a higher quality gif

- README.md
Move bash builtin programs to their category group.
> Update programs in bash builtins

- README.md
New programs added from the issues resolved.
> Added programs from Issues resolved

- Dockerfile.demo
- Use Dockerfile.demo instead
- Fix welcome message displayed when session
is created
> Use Dockerfile-demo

- README.md
Shred,localectl,makepkg added to the supported program list
> Supported programs

- README.md
Add new programs:
- `fdupes`
- `apt-mark`
- `hostnamectl`
- `ps`
- `pstree`
- `swapoff`
> New supported programs

- README.md
Programs added: unlink, usermod, lsusb, tput, xdg-open
> Supported program list updated

- README.md
xdg-mime, inxi, age, pbcopy, yum
> New programs added to the support list

- README.md
repo,fold,unalias,alias,npx,swift,rbenv Added to the supported program list
> Programs added

- README.md
Programs added: gv, zapier, mdbook, port, dnf, bpkg, synaptic
> First list of p3 March Tickets

- README.md
Tickets Resolved
#350, #380, #388, #394, #395, #399, #403, #406, #407, #408
Programs added:
perf
apachectl
umount
add-apt-repository
pkg
snap
complete
readonly
> April p1 tickets part 1

- README.md
Tickets closed
#387 
#390  
#381 
#385
#391
#397
#400
#402
Programs added
etcdctl
dpkg-reconfigure
terraform
ctr
> April P2 tickets part 2

- README.md
Closed Tickets
Part 3
#400
#402
#405
#410
#412
#421
#422
#424
Part 4
#429
#433
#435
#436
#446
#447
#449
#453
#458
#459
#460
Programs added
modinfo
webpack
crew
grubby
zypper
getent
gpasswd
pwdx
wg
> April P2 tickets part 3 and 4

- README.md
Resolved tickets
#441
#438
#414
#389
#375
#378
#383
#425
#374
Added programs
source
ld
rpmgraph
bindkey
cmake
rabbitmqctl
rpmbuild
> April P3 tickets Part 2

- README.md
Closed tickets
#444
#461
#463
#467
#468
#473
#477
#478
#481
#484
Added programs
yum-config-manager
sysctl
xcode-select
> May P1 Tickets
